data:
  prob_train: 0.7
  prob_test: 0.1
  crop_size: null
  use_views_annotations: true
  
  training_size:
  - 224
  - 224
  #delimiter: _
  maxvalues: null
  
  root_folder: /home/aalbiol/Downloads/shinyRotten
  terminaciones: ".npz" # Para cimgs todos los canales van en un solo archivo .cimg
  channel_list:
  - R 
  - G 
  - B 


  train_list_name: kk.txt
  val_list_name: kk.txt
  test_list_name: lista_shiny.txt
# Se emplean para crear listas de train-val-test
                 
              

model:
  defect_types:
  - rotten
  - surface
  num_channels_input: 3
  model_version: 50

train:
  batch_size: 8
  epochs: 20
  in_memory: true
  initial_model: null
  label_smoothing: 0.00
  learning_rate: 0.01
  optimizer: sgd
  num_workers: 0
  output:
    model_file: s90_patch_Alba6_from_zeroRGB.pkl
    path: out_models
  p_dropout: 0.4
  unfreeze_epoch: 30
  warmup: 0
  weights_decay: 0.01
  logname: s90_patch_Alba6_from_zeroRGB
  focal_loss_gamma: 2
  focal_loss_alpha: 0.7 # Para la clase positiva

  augmentation:
    random_rotation: 30
    brightness: 
    - 0.8
    - 1.3
    contrast:
    - 0.8
    - 1.3
    hue: 0.01
    saturation: 0.15
    blur:
    - 0.1
    - 1.5
    affine:
      scale:
      - 0.8
      - 1.1
      shear: 15
      translate: 
      - 0.0
      - 0.0
      degrees: 20

evaluate:
  model_dir: out_models
  model_file: s90_patch_Alba6_from_zeroRGB.pkl
  
  report_dir: out_evaluate_shiny_soloRGB
  train_predictions: train_scores.json
  val_predictions: val_scores.json
  test_predictions: test_scores.json  
  aucs: aucs.json


