stages:
  split_train_val:
    cmd: python ../src_clasificacion_vistas/data/MIL_split_train_val.py config/config.yaml
    deps:
    - ../src_clasificacion_vistas/data/MIL_split_train_val.py
    params:
    - config/config2.yaml:
      - data
    outs:
    - data/lote1/jsons/train_list.txt
    - data/lote1/jsons/val_list.txt
       
    - data/lote2/20230419_120236_DeformesDoblesEncoder/jsons/train_list.txt
    - data/lote2/20230419_100534_BuenoEncoder/jsons/train_list.txt
    - data/lote2/20230419_114356_CicatrizDefSupEncoder/jsons/train_list.txt
    - data/lote2/20230419_113002_LagrimaEncoder/jsons/train_list.txt
    - data/lote2/20230419_122528_VerdeRojoEncoder/jsons/train_list.txt
    - data/lote2/20230419_121536_BlandoEncoder/jsons/train_list.txt
    - data/lote2/20230419_115631_DestrioRotaEncoder/jsons/train_list.txt
    - data/lote2/20230419_112500_BuenoEncoder/jsons/train_list.txt
    - data/lote2/20230419_122046ArrugadoEncoder/jsons/train_list.txt
    - data/lote2/20230419_115102_HojaRaboConDeformeEncoder/jsons/train_list.txt

    - data/lote2/20230419_120236_DeformesDoblesEncoder/jsons/val_list.txt
    - data/lote2/20230419_100534_BuenoEncoder/jsons/val_list.txt
    - data/lote2/20230419_114356_CicatrizDefSupEncoder/jsons/val_list.txt
    - data/lote2/20230419_113002_LagrimaEncoder/jsons/val_list.txt
    - data/lote2/20230419_122528_VerdeRojoEncoder/jsons/val_list.txt
    - data/lote2/20230419_121536_BlandoEncoder/jsons/val_list.txt
    - data/lote2/20230419_115631_DestrioRotaEncoder/jsons/val_list.txt
    - data/lote2/20230419_112500_BuenoEncoder/jsons/val_list.txt
    - data/lote2/20230419_122046ArrugadoEncoder/jsons/val_list.txt
    - data/lote2/20230419_115102_HojaRaboConDeformeEncoder/jsons/val_list.txt


  train:
    cmd: python ../src_clasificacion_vistas/train/trainPatchMIL.py config/config.yaml
    deps:
    - ../src_clasificacion_vistas/train/trainMIL.py


    params:
    - config/config2.yaml:
      - data
      - train
      - model 	
    outs:
    - out_models/arandanos2.pkl

  evaluate:
    cmd: python ../src_clasificacion_vistas/evaluate/evaluateMIL.py config/config.yaml 
    deps:
    - ../src_clasificacion_vistas/evaluate/evaluateMIL.py
    - out_models/arandanos2.pkl
    params:
    - config/config2.yaml:
      - data
      - evaluate
      - model 	
    outs:
    - out_evaluate/aucs.json
    - out_evaluate/train_scores.json
    - out_evaluate/val_scores.json
  
  report:
    cmd: jupyter nbconvert --to notebook --execute reports/analisis_prestaciones.ipynb
    deps:
    - reports/analisis_prestaciones.ipynb
    - out_evaluate/aucs.json
    - out_evaluate/train_scores.json
    - out_evaluate/val_scores.json    
    outs:
    - reports/analisis_prestaciones.nbconvert.ipynb


  

