stages:

     
  train:
    cmd: python ../src_clasificacion_vistas/train/trainPatchMIL_Lists.py config2/configSara.yaml
    deps:
    - ../src_clasificacion_vistas/train/trainMIL.py


    params:
    - config2/configSara.yaml
      - data
      - train
      - model 	
    outs:
    - out_models/s90_patch_imgsSara.pkl

  evaluate:
    cmd: python ../src_clasificacion_vistas/evaluate/evaluatePatchMIL_Lists.py config2/configSara.yaml
    deps:
    - ../src_clasificacion_vistas/evaluate/evaluatePatchMIL_Lists.py
    - out_models/s90_patch_imgsSara.pkl
    params:
    - - config2/configSara.yaml
      - data
      - evaluate
      - model 	
    outs:
    - out_evaluate_imgsSara/aucs.json
    - out_evaluate_imgsSara/train_scores.json
    - out_evaluate_imgsSara/val_scores.json
  
  # report:
  #   cmd: jupyter nbconvert --to notebook --execute reports/analisis_prestaciones.ipynb
  #   deps:
  #   - reports/analisis_prestaciones.ipynb
  #   - out_evaluate/aucs.json
  #   - out_evaluate/train_scores.json
  #   - out_evaluate/val_scores.json    
  #   outs:
  #   - reports/analisis_prestaciones.nbconvert.ipynb


  

