stages:
     
  train:
    cmd: python ../src_view_segmentation/train/trainMIL.py config/config_segm.yaml
    deps:
    - ../src_view_segmentation/train/trainMIL.py 


    params:
    - config/config_segm.yaml:
      - data
      - train
      - model 	
    outs:
    - out_models/s90_segmentacion.pkl

  evaluate:
    cmd: python ../src_clasificacion_vistas/evaluate/evaluatePatchMIL.py config/config.yaml 
    deps:
    - ../src_clasificacion_vistas/evaluate/evaluatePatchMIL.py
    - out_models/orange_s90.pkl
    params:
    - config/config2.yaml:
      - data
      - evaluate
      - model 	
    outs:
    - out_evaluate/aucs.json
    - out_evaluate/train_scores.json
    - out_evaluate/val_scores.json
  
  # report:
  #   cmd: jupyter nbconvert --to notebook --execute reports/analisis_prestaciones.ipynb
  #   deps:
  #   - reports/analisis_prestaciones.ipynb
  #   - out_evaluate/aucs.json
  #   - out_evaluate/train_scores.json
  #   - out_evaluate/val_scores.json    
  #   outs:
  #   - reports/analisis_prestaciones.nbconvert.ipynb


  

