stages:
  split_train_val:
    cmd: python ../src_clasificacion_vistas/data/MIL_split_train_val.py config/config.yaml
    deps:
    - ../src_clasificacion_vistas/data/MIL_split_train_val.py
    params:
    - config/config.yaml:
      - data
    outs:
    - data/lote1/jsons/train_list.txt
    - data/lote1/jsons/val_list.txt
       



  train:
    cmd: python ../src_clasificacion_vistas/train/trainPatchMIL.py config/config.yaml
    deps:
    - ../src_clasificacion_vistas/train/trainMIL.py


    params:
    - config/config2.yaml:
      - data
      - train
      - model 	
    outs:
    - out_models/orange_s90.pkl

  evaluate:
    cmd: python ../src_clasificacion_vistas/evaluate/evaluatePatchMIL.py config/config.yaml 
    deps:
    - ../src_clasificacion_vistas/evaluate/evaluatePatchMIL.py
    - out_models/orange_s90.pkl
    params:
    - config/config2.yaml:
      - data
      - evaluate
      - model 	
    outs:
    - out_evaluate/aucs.json
    - out_evaluate/train_scores.json
    - out_evaluate/val_scores.json
  
  # report:
  #   cmd: jupyter nbconvert --to notebook --execute reports/analisis_prestaciones.ipynb
  #   deps:
  #   - reports/analisis_prestaciones.ipynb
  #   - out_evaluate/aucs.json
  #   - out_evaluate/train_scores.json
  #   - out_evaluate/val_scores.json    
  #   outs:
  #   - reports/analisis_prestaciones.nbconvert.ipynb


  

