data:
  prob_train: 0.8
  crop_size: null
  
  training_size:
  - 224
  - 224
  #delimiter: _
  maxvalues: null
  
  root_folder: data
  terminaciones: ".npz" # Para cimgs todos los canales van en un solo archivo .cimg
  channel_list:
  - R 
  - G 
  - B 
  - NIR
  - UV

  train:
  - - train_list.txt
    - mandarins/clementine/KDC/20220808_154231_Img_20220808_154156produccionClementina
    - mandarins/clementine/KDC/20220808_154231_Img_20220808_154156produccionClementina
  - - train_list.txt    
    - mandarins/clementine/KDC/20220803_225931_CLEMENTINE_Encoder_SURFACE1
    - mandarins/clementine/KDC/20220803_225931_CLEMENTINE_Encoder_SURFACE1    
  - - train_list.txt
    - mandarins/clementine/KDC/20220804_221439_CLEMENTINE_ENCODER_Hollow
    - mandarins/clementine/KDC/20220804_221439_CLEMENTINE_ENCODER_Hollow    
  - - train_list.txt
    - mandarins/clementine/KDC/20220803_230921_CLEMENTINE_Encoder_OilSpots
    - mandarins/clementine/KDC/20220803_230921_CLEMENTINE_Encoder_OilSpots    
  - - train_list.txt
    - mandarins/clementine/KDC/20220803_230515_CLEMENTINE_Encoder_Creasing1
    - mandarins/clementine/KDC/20220803_230515_CLEMENTINE_Encoder_Creasing1    
  - - train_list.txt
    - mandarins/clementine/KDC/20220808_154209_Img_20220808_154156produccionClementina
    - mandarins/clementine/KDC/20220808_154209_Img_20220808_154156produccionClementina    
  - - train_list.txt
    - mandarins/clementine/KDC/20220803_231441_CLEMENTINE_Encoder_Good
    - mandarins/clementine/KDC/20220803_231441_CLEMENTINE_Encoder_Good
  - - train_list.txt
    - mandarins/clementine/KDC/20220803_230825_CLEMENTINE_Encoder_Geens
    - mandarins/clementine/KDC/20220803_230825_CLEMENTINE_Encoder_Geens    
  - - train_list.txt
    - mandarins/clementine/KDC/20220803_231126_CLEMENTINE_Encoder_Scar
    - mandarins/clementine/KDC/20220803_231126_CLEMENTINE_Encoder_Scar    
  - - train_list.txt
    - mandarins/clementine/KDC/20220803_230703_CLEMENTINE_Encoder_rot
    - mandarins/clementine/KDC/20220803_230703_CLEMENTINE_Encoder_rot    
  - - train_list.txt
    - mandarins/clementine/KDC/20220808_154219_Img_20220808_154156produccionClementina
    - mandarins/clementine/KDC/20220808_154219_Img_20220808_154156produccionClementina
  - - train_list.txt
    - mandarins/clementine/KDC/20220803_231323_CLEMENTINE_Encoder_Skin
    - mandarins/clementine/KDC/20220803_231323_CLEMENTINE_Encoder_Skin
  - - train_list.txt
    - mandarins/nardocot/manfredi
    - mandarins/nardocot/manfredi
  - - train_list.txt
    - mandarins/tango/KDC/20220804_230331_TANGO_encoder_Scar
    - mandarins/tango/KDC/20220804_230331_TANGO_encoder_Scar
  - - train_list.txt
    - mandarins/tango/KDC/20220806_185520_tango_ENCODER_MANCHAS
    - mandarins/tango/KDC/20220806_185520_tango_ENCODER_MANCHAS
  - - train_list.txt
    - mandarins/tango/KDC/20220805_180026_tangoPROD
    - mandarins/tango/KDC/20220805_180026_tangoPROD
  - - train_list.txt
    - mandarins/tango/KDC/20220805_225459_tango_ENCODER_scars
    - mandarins/tango/KDC/20220805_225459_tango_ENCODER_scars
  - - train_list.txt
    - mandarins/tango/KDC/20220804_230730_TANGO_encoder_good
    - mandarins/tango/KDC/20220804_230730_TANGO_encoder_good
  - - train_list.txt
    - mandarins/tango/KDC/20220804_230522_TANGO_encoder_SkinDamage
    - mandarins/tango/KDC/20220804_230522_TANGO_encoder_SkinDamage
  - - train_list.txt
    - mandarins/tango/KDC/20220805_172517_tango_PROD
    - mandarins/tango/KDC/20220805_172517_tango_PROD
  - - train_list.txt 
    - mandarins/tango/KDC/20220806_185859_tango_ENCODER_ROTAS
    - mandarins/tango/KDC/20220806_185859_tango_ENCODER_ROTAS
  - - train_list.txt
    - mandarins/tango/KDC/20220804_230235_TANGO_encoder_Surface
    - mandarins/tango/KDC/20220804_230235_TANGO_encoder_Surface
  - - train_list.txt
    - mandarins/tango/KDC/20220805_231606_TANGO_ENCODER_surface
    - mandarins/tango/KDC/20220805_231606_TANGO_ENCODER_surface
  - - train_list.txt
    - oranges/navel/manfredi
    - oranges/navel/manfredi
  - - train_list.txt
    - oranges/navel/KDC/20220810_021928_Encoder_Buenas
    - oranges/navel/KDC/20220810_021928_Encoder_Buenas
  - - train_list.txt
    - oranges/navel/KDC/20220810_022231_Encoder_decay
    - oranges/navel/KDC/20220810_022231_Encoder_decay
  - - train_list.txt
    - oranges/navel/KDC/20220829_214906_prod_naranja_plu
    - oranges/navel/KDC/20220829_214906_prod_naranja_plu
  - - train_list.txt
    - oranges/navel/KDC/20220829_214322_prod_naranja_plu
    - oranges/navel/KDC/20220829_214322_prod_naranja_plu
  - - train_list.txt
    - oranges/navel/KDC/20220810_022140_Encoder_oilspot
    - oranges/navel/KDC/20220810_022140_Encoder_oilspot
                 
                
  
  

  val:
  - - val_list.txt
    - mandarins/clementine/KDC/20220808_154231_Img_20220808_154156produccionClementina
    - mandarins/clementine/KDC/20220808_154231_Img_20220808_154156produccionClementina
  - - val_list.txt    
    - mandarins/clementine/KDC/20220803_225931_CLEMENTINE_Encoder_SURFACE1
    - mandarins/clementine/KDC/20220803_225931_CLEMENTINE_Encoder_SURFACE1    
  - - val_list.txt
    - mandarins/clementine/KDC/20220804_221439_CLEMENTINE_ENCODER_Hollow
    - mandarins/clementine/KDC/20220804_221439_CLEMENTINE_ENCODER_Hollow    
  - - val_list.txt
    - mandarins/clementine/KDC/20220803_230921_CLEMENTINE_Encoder_OilSpots
    - mandarins/clementine/KDC/20220803_230921_CLEMENTINE_Encoder_OilSpots    
  - - val_list.txt
    - mandarins/clementine/KDC/20220803_230515_CLEMENTINE_Encoder_Creasing1
    - mandarins/clementine/KDC/20220803_230515_CLEMENTINE_Encoder_Creasing1    
  - - val_list.txt
    - mandarins/clementine/KDC/20220808_154209_Img_20220808_154156produccionClementina
    - mandarins/clementine/KDC/20220808_154209_Img_20220808_154156produccionClementina    
  - - val_list.txt
    - mandarins/clementine/KDC/20220803_231441_CLEMENTINE_Encoder_Good
    - mandarins/clementine/KDC/20220803_231441_CLEMENTINE_Encoder_Good
  - - val_list.txt
    - mandarins/clementine/KDC/20220803_230825_CLEMENTINE_Encoder_Geens
    - mandarins/clementine/KDC/20220803_230825_CLEMENTINE_Encoder_Geens    
  - - val_list.txt
    - mandarins/clementine/KDC/20220803_231126_CLEMENTINE_Encoder_Scar
    - mandarins/clementine/KDC/20220803_231126_CLEMENTINE_Encoder_Scar    
  - - val_list.txt
    - mandarins/clementine/KDC/20220803_230703_CLEMENTINE_Encoder_rot
    - mandarins/clementine/KDC/20220803_230703_CLEMENTINE_Encoder_rot    
  - - val_list.txt
    - mandarins/clementine/KDC/20220808_154219_Img_20220808_154156produccionClementina
    - mandarins/clementine/KDC/20220808_154219_Img_20220808_154156produccionClementina
  - - val_list.txt
    - mandarins/clementine/KDC/20220803_231323_CLEMENTINE_Encoder_Skin
    - mandarins/clementine/KDC/20220803_231323_CLEMENTINE_Encoder_Skin
  - - val_list.txt
    - mandarins/nardocot/manfredi
    - mandarins/nardocot/manfredi
  - - val_list.txt
    - mandarins/tango/KDC/20220804_230331_TANGO_encoder_Scar
    - mandarins/tango/KDC/20220804_230331_TANGO_encoder_Scar
  - - val_list.txt
    - mandarins/tango/KDC/20220806_185520_tango_ENCODER_MANCHAS
    - mandarins/tango/KDC/20220806_185520_tango_ENCODER_MANCHAS
  - - val_list.txt
    - mandarins/tango/KDC/20220805_180026_tangoPROD
    - mandarins/tango/KDC/20220805_180026_tangoPROD
  - - val_list.txt
    - mandarins/tango/KDC/20220805_225459_tango_ENCODER_scars
    - mandarins/tango/KDC/20220805_225459_tango_ENCODER_scars
  - - val_list.txt
    - mandarins/tango/KDC/20220804_230730_TANGO_encoder_good
    - mandarins/tango/KDC/20220804_230730_TANGO_encoder_good
  - - val_list.txt
    - mandarins/tango/KDC/20220804_230522_TANGO_encoder_SkinDamage
    - mandarins/tango/KDC/20220804_230522_TANGO_encoder_SkinDamage
  - - val_list.txt
    - mandarins/tango/KDC/20220805_172517_tango_PROD
    - mandarins/tango/KDC/20220805_172517_tango_PROD
  - - val_list.txt
    - mandarins/tango/KDC/20220806_185859_tango_ENCODER_ROTAS
    - mandarins/tango/KDC/20220806_185859_tango_ENCODER_ROTAS
  - - val_list.txt
    - mandarins/tango/KDC/20220804_230235_TANGO_encoder_Surface
    - mandarins/tango/KDC/20220804_230235_TANGO_encoder_Surface
  - - val_list.txt
    - mandarins/tango/KDC/20220805_231606_TANGO_ENCODER_surface
    - mandarins/tango/KDC/20220805_231606_TANGO_ENCODER_surface
  - - val_list.txt
    - oranges/navel/manfredi
    - oranges/navel/manfredi
  - - val_list.txt
    - oranges/navel/KDC/20220810_021928_Encoder_Buenas
    - oranges/navel/KDC/20220810_021928_Encoder_Buenas
  - - val_list.txt
    - oranges/navel/KDC/20220810_022231_Encoder_decay
    - oranges/navel/KDC/20220810_022231_Encoder_decay
  - - val_list.txt
    - oranges/navel/KDC/20220829_214906_prod_naranja_plu
    - oranges/navel/KDC/20220829_214906_prod_naranja_plu
  - - val_list.txt
    - oranges/navel/KDC/20220829_214322_prod_naranja_plu
    - oranges/navel/KDC/20220829_214322_prod_naranja_plu
  - - val_list.txt
    - oranges/navel/KDC/20220810_022140_Encoder_oilspot
    - oranges/navel/KDC/20220810_022140_Encoder_oilspot        

model:
  defect_types:
  - green
  - hollow
  #- insect
  - light_scars
  - oil_spots
  - plu_stickers
  - rotten
  - scars
  - skin_breakdown
  - surface
  num_channels_input: 5
  model_version: 50

train:
  batch_size: 8
  epochs: 80
  in_memory: true
  initial_model: null #out_models/s90_patch_ini.pkl
  label_smoothing: 0.00
  learning_rate: 0.03
  optimizer: sgd
  num_workers: -1
  output:
    model_file: s90_patch_224.pkl
    path: out_models
  p_dropout: 0.4
  unfreeze_epoch: 30
  warmup: 3
  weights_decay: 0.01
  logname: s90_patch_vistas_224_reanot3_cristina
  focal_loss_gamma: 2
  focal_loss_alpha: 0.5 # Para la clase positiva

  augmentation:
    random_rotation: 30
    brightness: 
    - 0.8
    - 1.3
    contrast:
    - 0.8
    - 1.3
    hue: 0.01
    saturation: 0.15
    blur:
    - 0.1
    - 1.5
    affine:
      scale:
      - 0.8
      - 1.1
      shear: 15
      translate: 
      - 0.0
      - 0.0
      degrees: 20

evaluate:
  model_dir: out_models
  model_file: s90_patch_224.pkl
  
  report_dir: out_evaluate_patch_224_reanot3
  train_predictions: train_scores.json
  val_predictions: val_scores.json
  aucs: aucs.json


predict:
  model_dir: out_models
  model_file: s90_patch_224.pkl
  patron: "*.npz"
  
  report_dir: out_predict
    